### ISSUE TITLE
Vagrant tar fail on macOS

### ISSUE THREAD

**Issue by cjlawson02** [robotpy/roborio-opencv#6]
Affects line 21 in build.sh:
```shell
tar -xf data.tar.gz -C "$SYSROOT"
```
Will exit 1... says `Operation not permitted` even with 777 perms. Command works in Vanilla macOS.

Workaround:
- Option 1:
  - Run `./build.sh` in a vanilla linux environment
- Option 2:
  - Run line 21 outside of Vagrant and remove line 21

**Comment by virtuald** [comment]
OBE
